import pyautogui as memel

memel.mouseInfo()

memel.press ("win")
memel.sleep (1)
memel.write ("google chrome")
memel.sleep (2)
memel.press("enter")
memel.sleep (2)
memel.click (1041,580)
memel.write ("instagram")
memel.sleep (3)
memel.press("enter")
memel.sleep (2)
memel.moveTo(376,382)
memel.click()
memel.sleep (2)
memel.moveTo(669,470)
memel.click()
memel.sleep (2)
memel.write ("m.ferreirw_")
memel.moveTo(670,513)
memel.click()
memel.sleep (2)
memel.write ("mellyssa15")
memel.press("enter")